# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Funny' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SQLite.swift'

end
